version: '3'

services:
  cloud-config-server:
    image: rmolin/cloud-config-server
    environment:
      - name=value
      - server.port=8888
      - spring.cloud.config.server.git.uri=https://gitlab.cpr.dk/rmolin2/config-server-example.git
      - spring.cloud.config.server.git.clone-on-start=true
      - spring.cloud.config.server.git.default-label=master

  cloud-config-client:
    image: cloud-config-client
    ports:
      - "8080:8080"
    environment:
      - spring.application.name=config-client
      - spring.profiles.active=development
      - spring.config.import=configserver:http://cloud-config-server:8888
    restart: on-failure
    depends_on:
      - cloud-config-server




