version: '3'

services:
  rabbitmq:
    image: rabbitmq:3

  cloud-config-server:
    image: rmolin/cloud-config-server
    ports:
      - "8888:8888"
    environment:
      - server.port=8888
      - spring.cloud.config.server.git.uri=https://github.com/RuneMolin/cloud-config-repo.git
      - spring.cloud.config.server.git.clone-on-start=true
      - spring.cloud.config.server.git.default-label=main
      - spring.rabbitmq.host=rabbitmq
      - spring.rabbitmq.port=5672
      - spring.rabbitmq.username=guest
      - spring.rabbitmq.password=guest
    restart: on-failure
    depends_on:
      - rabbitmq

  cloud-config-client:
    image: rmolin/cloud-config-client
    ports:
      - "8080:8080"
    environment:
      - spring.application.name=config-client
      - spring.profiles.active=development
      - spring.config.import=configserver:http://cloud-config-server:8888
      - spring.rabbitmq.host=rabbitmq
      - spring.rabbitmq.port=5672
      - spring.rabbitmq.username=guest
      - spring.rabbitmq.password=guest
      - spring.cloud.bus.enabled=true
      - spring.cloud.bus.refresh.enabled=true
    restart: on-failure
    depends_on:
      - cloud-config-server
