name: ci

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up JDK 11
        uses: actions/setup-java@v2.3.1
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'maven'

      - name: Build with maven
        run: ./mvnw -B package --file pom.xml

      - name: Publish server image
        run: ./mvnw -B jib:build -pl server

      - name: Publish client image
        run: ./mvnw -B jib:build -pl client

